# Site settings
title: Joshua Scharf
subtitle: A developer with an eye for design
email: jscharf@ackroo.com
description: Built with Jekyll and hosted on Github Pages.
baseurl: ""
url: "https://jscharf.github.io"
github_username: jscharf
linkedin_username: joshscharf

# Build settings
markdown: kramdown
